settings:
  # default folders
  inputDir: notes
  outputDir: out
  outputNotesSubDir: posts
  currentImgDir: images
  outputImgDir: src/img/post
  markdownLinkImageDir: img/post


frontMatterTemplate:
  layout: post
  title:
  tags: [Uncategorized]
  toc: true
  icon: /img/cats/data-science.svg 
  keywords:
  date:
